---
output: html_document
---
### CDS- Creative Data Solutions 
#### Terms of Service
#### Last Revised: Dec 03 2015


The following terms and conditions govern all use of the Creative Data Solutions website and all content, services and products available at or through the website, including, but not limited to, Creative Data Solutions Forum Software, Creative Data Solutions Support Forums and the Creative Data Solutions Hosting service ("Hosting"), (taken together, the Website). The Website is owned and operated by CDS- Creative Data Solutions ("CDS"). The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, Creative Data Solutions’s Privacy Policy and Community Guidelines) and procedures that may be published from time to time on this Site by CDS (collectively, the "Agreement").

Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by CDS, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.


1. Your Creative Data Solutions Account

If you create an account on the Website, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account. You must immediately notify CDS of any unauthorized uses of your account or any other breaches of security. CDS will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.


2. Responsibility of Contributors

If you post material to the Website, post links on the Website, or otherwise make (or allow any third party to make) material available by means of the Website (any such material, "Content"), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:

the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;
if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;
you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;
the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;
the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);
the Content is not pornographic, does not contain threats or incite violence, and does not violate the privacy or publicity rights of any third party;
your content is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, blogs and web sites, and similar unsolicited promotional methods;
your content is not named in a manner that misleads your readers into thinking that you are another person or company; and
you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by CDS or otherwise.

3. User Content License

User contributions are licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. Without limiting any of those representations or warranties, CDS has the right (though not the obligation) to, in CDS’s sole discretion (i) refuse or remove any content that, in CDS’s reasonable opinion, violates any CDS policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in CDS’s sole discretion. CDS will have no obligation to provide a refund of any amounts previously paid.


4. Payment and Renewal

General Terms

Optional paid services or upgrades may be available on the Website. When utilizing an optional paid service or upgrade, you agree to pay CDS the monthly or annual subscription fees indicated. Payments will be charged on a pre-pay basis on the day you begin utilizing the service or upgrade and will cover the use of that service or upgrade for a monthly or annual subscription period as indicated. These fees are not refundable.

Automatic Renewal

Unless you notify CDS before the end of the applicable subscription period that you want to cancel a service or upgrade, your subscription will automatically renew and you authorize us to collect the then-applicable annual or monthly subscription fee (as well as any taxes) using any credit card or other payment mechanism we have on record for you. Subscriptions can be canceled at any time.


5. Services

Hosting, Support Services

Optional Hosting and Support services may be provided by CDS under the terms and conditions for each such service. By signing up for a Hosting/Support or Support services account, you agree to abide by such terms and conditions.


6. Responsibility of Website Visitors

CDS has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, CDS does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. CDS disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.


7. Content Posted on Other Websites

We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Creative Data Solutions links, and that link to Creative Data Solutions. CDS does not have any control over those non-Creative Data Solutions websites and webpages, and is not responsible for their contents or their use. By linking to a non-Creative Data Solutions website or webpage, CDS does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. CDS disclaims any responsibility for any harm resulting from your use of non-Creative Data Solutions websites and webpages.


8. Copyright Infringement and DMCA Policy

As CDS asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by Creative Data Solutions violates your copyright, and if this website resides in the USA, you are encouraged to notify CDS in accordance with CDS’s Digital Millennium Copyright Act ("DMCA") Policy. CDS will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. CDS will terminate a visitor’s access to and use of the Website if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of CDS or others. In the case of such termination, CDS will have no obligation to provide a refund of any amounts previously paid to CDS.


9. Intellectual Property

This Agreement does not transfer from CDS to you any CDS or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with CDS. CDS, Creative Data Solutions, the Creative Data Solutions logo, and all other trademarks, service marks, graphics and logos used in connection with Creative Data Solutions, or the Website are trademarks or registered trademarks of CDS or CDS’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any CDS or third-party trademarks.


10. Advertisements

CDS reserves the right to display advertisements on your content unless you have purchased an Ad-free Upgrade or a Services account.


11. Attribution

CDS reserves the right to display attribution links such as ‘Powered by Creative Data Solutions,’ theme author, and font attribution in your content footer or toolbar. Footer credits and the Creative Data Solutions toolbar may not be removed regardless of upgrades purchased.


12. Changes

CDS reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. CDS may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.


13. Termination

CDS may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your Creative Data Solutions account (if you have one), you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.


14. Disclaimer of Warranties

THE SERVICE IS PROVIDED "AS IS." CDS MAKES NO REPRESENTATION OR WARRANTY OF ANY KIND WHATSOEVER RELATING TO THE SERVICE, LINKED SITES, OR OTHER CONTENT THAT MAY BE ACCESSIBLE DIRECTLY OR INDIRECTLY THROUGH THE SERVICE. CDS EXPRESSLY DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW ANY AND ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND WARRANTIES AGAINST INFRINGEMENT OF ANY THIRD-PARTY INTELLECTUAL PROPERTY OR PROPRIETARY RIGHTS. FURTHER, THERE IS NO WARRANTY THAT THE SERVICE WILL MEET YOUR NEEDS OR REQUIREMENTS OR THE NEEDS OR REQUIREMENTS OF ANY OTHER PERSON.
WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, CDS MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED: (A) THAT THE INFORMATION, GRAPHS, CHARTS, DATA AND OTHER CONTENT PROVIDED THROUGH THE SERVICE WILL BE ACCURATE, RELIABLE, AND COMPLETE AND FREE FROM ERRORS, OMISSIONS, DEFECTS, OR DELAYS IN OPERATION; (B) THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (C) THAT DEFECTS OR ERRORS IN THE SERVICE WILL BE CORRECTED; OR (D) THAT THE CONTENT ON THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.


15. Limitation of Liability

IN NO EVENT WILL CDS OR ITS AFFILIATES, OR ANY PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICE BE LIABLE FOR ANY DIRECT, INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL, OR PUNITIVE DAMAGES ARISING OUT OF YOUR ACCESS, USE, MISUSE, OR INABILITY TO USE THE CONTENT, SERVICE OR ANY LINKED SITES, OR IN CONNECTION WITH ANY LOST OR CORRUPTED DATA OR USER CONTENT OR UNAUTHORIZED THIRD PARTY ACCESS TO ANY DATA OR USER CONTENT, FAILURE OF PERFORMANCE,DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, OR LINE OR SYSTEM FAILURE. IN THE EVENT THAT YOU HAVE A DISPUTE WITH ANOTHER USER IN ANY WAY CONNECTED WITH YOUR USE OF THE SERVICE, YOU RELEASE CDS FROM ANY CLAIMS, DEMANDS, AND DAMAGES OF EVERY KIND AND NATURE ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH A DISPUTE. THE MAXIMUM TOTAL LIABILITY OF CDS, ITS AFFILIATES AND LICENSORS TO YOU FOR ANY CLAIM UNDER THIS AGREEMENT, IS THE LESSER OF: (A) THE AMOUNT RECEIVED BY CDS FROM YOU DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM OR (B) $100.  
EACH PROVISION OF THIS AGREEMENT THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS TO ALLOCATE THE RISKS UNDER THIS AGREEMENT BETWEEN THE PARTIES. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND CDS. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THIS AGREEMENT.
THESE LIMITATIONS APPLY WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF CDS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, AND EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF DAMAGES, CDS'S LIABILITY IN SUCH JURISDICTIONS WILL BE LIMITED TO THE EXTENT PERMITTED BY LAW.


16. Indemnification

You will indemnify, defend and hold CDS and its licensors harmless (and our respective employees, directors, agents, affiliates and representatives) from and against any and all claims, costs, losses, damages, judgments, tax assessments, penalties, interest, and expenses (including without limitation reasonable attorneys’ fees) arising out of any claim, action, audit, investigation, inquiry, or other proceeding instituted by a person or entity that arises out of or relates to: (i) your use of the Service or any activity on the Service via your account, (ii) your violation of any provision of these Terms including any of your covenants, warranties or representations hereunder, (iii) any User Content uploaded to CDS, or (iv) the collection, storage, or disclosure of personal or health data or disclosure of personal information or health data in violation of applicable law, or any failure to obtain consents or authorizations for such data required by applicable law. CDS reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims.  You may not settle any matter without the prior written consent from CDS.  


17. Miscellaneous

This Agreement constitutes the entire agreement between CDS and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of CDS, or by the posting by CDS of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in San Francisco County, California. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in San Francisco, California, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; CDS may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.

This document is CC-BY-SA.